#!/usr/bin/env Rscript
# packages/historicaldata/data-raw/make_sample_data.R
#
# Deterministic, seeded generator for the bundled sample Parquet fixtures at
# inst/extdata/sample/*.parquet. These fixtures back HD_USE_SAMPLE_DATA=1,
# the test-only resolver seam (see hd_dataset_source() in R/registry.R) that
# makes the package test suite hermetic against a live hf:// endpoint
# (issue #580 Phase 2).
#
# Provenance (reproducible-ingestion rule): every value below is synthetic,
# generated by this script from set.seed(42) and literal 2024 calendar
# dates -- NOT derived from any real market data, and NOT hand-typed. Ticker
# symbols reuse real large-cap US tickers as plausible labels only; the
# price/volume/metadata series attached to them are fabricated. Re-running
# this script reproduces byte-identical numeric content every time (Parquet
# writer metadata such as creation timestamps may differ). This discharges
# the technical debt the previous hand-committed sample_*.parquet files
# carried: no generator, no audit trail, no way to regenerate or extend them.
#
# Regenerate with (from the repo root, inside the project's Nix flake shell):
#   nix develop --command Rscript packages/historicaldata/data-raw/make_sample_data.R
#
# Design constraints (locked, #580 Phase 2 spec):
#   - equity_sample keeps the LEGACY 'adjusted' column name (not
#     'adjusted_close') so the #325 read-time alias path stays under test.
#   - equity_sample / crypto_sample 'date' is POSIXct (TIMESTAMP), matching
#     the real HF schema and exercising the #453 date-type probe.
#   - macro_sample / factors_sample 'date' is Date, matching the real HF
#     schema for those datasets.
#   - Column sets match packages/historicaldata/R/registry.R::hd_datasets()
#     schemas exactly (after the 'adjusted' -> 'adjusted_close' alias for
#     equity_daily).

suppressPackageStartupMessages({
  library(tibble)
})

set.seed(42)

# ---------------------------------------------------------------------------
# Locate output directory. Must be run from the repo root (the flake root),
# not from inside packages/historicaldata/.
# ---------------------------------------------------------------------------
out_dir <- file.path("packages", "historicaldata", "inst", "extdata", "sample")
if (!dir.exists(out_dir)) {
  stop(
    "Cannot find '", out_dir, "'. Run this script from the repo root, e.g.\n",
    "  nix develop --command Rscript packages/historicaldata/data-raw/make_sample_data.R"
  )
}

# ---------------------------------------------------------------------------
# Date helpers -- fixed literal 2024 ranges, no Sys.time()/Sys.Date().
# ---------------------------------------------------------------------------

# Return `n` consecutive weekday (Mon-Fri) dates starting at `start_date`.
.business_days <- function(start_date, n) {
  d <- as.Date(start_date)
  out <- vector("list", n)
  i <- 0L
  while (i < n) {
    if (!(weekdays(d) %in% c("Saturday", "Sunday"))) {
      i <- i + 1L
      out[[i]] <- d
    }
    d <- d + 1L
  }
  do.call(c, out)
}

EQUITY_DATES <- .business_days("2024-01-02", 32L)   # Tue 2024-01-02 .. (32 weekdays)
CRYPTO_DATES <- as.Date("2024-01-01") + 0:39         # 40 consecutive calendar days
MACRO_DATES  <- EQUITY_DATES                         # reuse equity's weekday calendar
FACTOR_DATES <- EQUITY_DATES

cat("EQUITY_DATES range:", format(min(EQUITY_DATES)), "..", format(max(EQUITY_DATES)),
    "(", length(EQUITY_DATES), "obs)\n")
cat("CRYPTO_DATES range:", format(min(CRYPTO_DATES)), "..", format(max(CRYPTO_DATES)),
    "(", length(CRYPTO_DATES), "obs)\n")

# ---------------------------------------------------------------------------
# Equity universe: AAPL, MSFT + 53 more large-cap US tickers (labels only;
# price series are synthetic). Total 55 tickers, keeping
# hd_tickers("equity_daily") length >= 50 a real assertion.
# ---------------------------------------------------------------------------
EQUITY_TICKERS <- c(
  "AAPL", "MSFT",
  "GOOGL", "AMZN", "NVDA", "TSLA", "META", "BRKB", "JPM", "V",
  "JNJ", "WMT", "PG", "MA", "HD", "CVX", "ABBV", "PFE", "KO", "PEP",
  "MRK", "COST", "TMO", "DIS", "ADBE", "CSCO", "XOM", "ACN", "MCD", "ABT",
  "DHR", "NKE", "LIN", "TXN", "NEE", "PM", "UNH", "VZ", "INTC", "WFC",
  "BMY", "RTX", "HON", "UPS", "T", "LOW", "ORCL", "IBM", "CAT", "GS",
  "BA", "SBUX", "MMM", "GE", "AMD"
)
stopifnot(length(EQUITY_TICKERS) == 55L, all(c("AAPL", "MSFT") %in% EQUITY_TICKERS))

CRYPTO_TICKERS <- c("BTC", "ETH")

# One deterministic base price per equity ticker (order fixed above, so
# regeneration is byte-stable given the same seed).
EQUITY_BASE_PRICE <- stats::setNames(
  round(runif(length(EQUITY_TICKERS), min = 20, max = 500), 2),
  EQUITY_TICKERS
)
# Keep AAPL/MSFT in a realistic large-cap range for readability.
EQUITY_BASE_PRICE[["AAPL"]] <- 185.00
EQUITY_BASE_PRICE[["MSFT"]] <- 370.00

CRYPTO_BASE_PRICE <- c(BTC = 42500, ETH = 2300)

# ---------------------------------------------------------------------------
# OHLCV generator (shared by equity + crypto)
# ---------------------------------------------------------------------------
.make_ohlcv <- function(ticker, dates, base_price, day_vol = 0.02,
                         adjusted_col = NULL, asset_class, updated_at) {
  n <- length(dates)
  rets <- rnorm(n, mean = 0.0002, sd = day_vol)
  close <- base_price * cumprod(1 + rets)
  prev_close <- c(base_price, close[-n])
  open <- prev_close * (1 + rnorm(n, 0, day_vol * 0.3))
  hi_lo_spread <- abs(rnorm(n, 0, day_vol * 0.5))
  high <- pmax(open, close) * (1 + hi_lo_spread)
  low  <- pmin(open, close) * (1 - hi_lo_spread)
  volume <- round(runif(n, 1e6, 8e7))

  out <- tibble::tibble(
    date   = dates,
    open   = round(open, 2),
    high   = round(high, 2),
    low    = round(low, 2),
    close  = round(close, 2),
    volume = volume,
    ticker = ticker,
    source = "synthetic",
    asset_class = asset_class,
    updated_at = updated_at
  )

  if (!is.null(adjusted_col)) {
    # Legacy pre-#325 column name 'adjusted' -- deliberately NOT renamed to
    # 'adjusted_close' here so the read-time alias in hd_ohlcv_single()/
    # hd_lazy() stays exercised by the hermetic test suite.
    out[[adjusted_col]] <- round(out$close * 0.99, 2)
    out <- out[, c("date", "open", "high", "low", "close", adjusted_col,
                   "volume", "ticker", "source", "asset_class", "updated_at")]
  }
  out
}

UPDATED_AT <- as.POSIXct("2024-03-15 00:00:00", tz = "UTC")

equity_rows <- lapply(EQUITY_TICKERS, function(tk) {
  .make_ohlcv(
    ticker = tk,
    dates = as.POSIXct(EQUITY_DATES, tz = "UTC"),
    base_price = EQUITY_BASE_PRICE[[tk]],
    day_vol = 0.018,
    adjusted_col = "adjusted",
    asset_class = "equity",
    updated_at = UPDATED_AT
  )
})
equity_sample <- dplyr::bind_rows(equity_rows)

crypto_rows <- lapply(CRYPTO_TICKERS, function(tk) {
  .make_ohlcv(
    ticker = tk,
    dates = as.POSIXct(CRYPTO_DATES, tz = "UTC"),
    base_price = CRYPTO_BASE_PRICE[[tk]],
    day_vol = 0.035,
    adjusted_col = NULL,
    asset_class = "crypto",
    updated_at = UPDATED_AT
  )
})
crypto_sample <- dplyr::bind_rows(crypto_rows)

# ---------------------------------------------------------------------------
# Metadata: one row per ticker (equities + crypto). Matches registry's
# 31-column `metadata` schema exactly.
# ---------------------------------------------------------------------------
n_eq <- length(EQUITY_TICKERS)
n_cr <- length(CRYPTO_TICKERS)

sectors <- sample(
  c("Technology", "Healthcare", "Financials", "Consumer Discretionary",
    "Consumer Staples", "Industrials", "Energy", "Communication Services"),
  n_eq, replace = TRUE
)

metadata_equity <- tibble::tibble(
  ticker              = EQUITY_TICKERS,
  dataset             = "equity_daily",
  long_name           = paste(EQUITY_TICKERS, "Inc."),
  exchange            = "NMS",
  full_exchange       = "NasdaqGS",
  currency            = "USD",
  instrument_type     = "EQUITY",
  sector              = sectors,
  industry            = paste(sectors, "Sub-Industry"),
  country             = "United States",
  market_cap          = round(runif(n_eq, 5e10, 3.5e12)),
  volume_avg          = round(runif(n_eq, 1e6, 8e7)),
  fifty_two_week_high = round(EQUITY_BASE_PRICE[EQUITY_TICKERS] * 1.25, 2),
  fifty_two_week_low  = round(EQUITY_BASE_PRICE[EQUITY_TICKERS] * 0.75, 2),
  expense_ratio       = NA_real_,
  yield_pct           = NA_real_,
  category            = NA_character_,
  fund_family         = NA_character_,
  nav_price           = NA_real_,
  beta_3yr            = round(runif(n_eq, 0.6, 1.6), 3),
  ytd_return          = round(runif(n_eq, -0.3, 0.4), 3),
  three_yr_return     = round(runif(n_eq, -0.2, 0.6), 3),
  start_date          = min(EQUITY_DATES),
  end_date            = max(EQUITY_DATES),
  total_obs           = length(EQUITY_DATES),
  missing_pct         = 0,
  yield_type          = NA_character_,
  short_name          = EQUITY_TICKERS,
  quote_type          = "EQUITY",
  asset_class         = "equity",
  source              = "synthetic"
)

metadata_crypto <- tibble::tibble(
  ticker              = CRYPTO_TICKERS,
  dataset             = "crypto_daily",
  long_name           = c("Bitcoin USD", "Ethereum USD"),
  exchange            = "CCC",
  full_exchange       = "CCC",
  currency            = "USD",
  instrument_type     = "CRYPTOCURRENCY",
  sector              = NA_character_,
  industry            = NA_character_,
  country             = NA_character_,
  market_cap          = round(runif(n_cr, 1e11, 1e12)),
  volume_avg          = round(runif(n_cr, 1e9, 5e10)),
  fifty_two_week_high = round(CRYPTO_BASE_PRICE[CRYPTO_TICKERS] * 1.4, 2),
  fifty_two_week_low  = round(CRYPTO_BASE_PRICE[CRYPTO_TICKERS] * 0.6, 2),
  expense_ratio       = NA_real_,
  yield_pct           = NA_real_,
  category            = NA_character_,
  fund_family         = NA_character_,
  nav_price           = NA_real_,
  beta_3yr            = NA_real_,
  ytd_return          = round(runif(n_cr, -0.3, 0.5), 3),
  three_yr_return     = round(runif(n_cr, -0.2, 1.0), 3),
  start_date          = min(CRYPTO_DATES),
  end_date            = max(CRYPTO_DATES),
  total_obs           = length(CRYPTO_DATES),
  missing_pct         = 0,
  yield_type          = NA_character_,
  short_name          = CRYPTO_TICKERS,
  quote_type          = "CRYPTOCURRENCY",
  asset_class         = NA_character_,
  source              = NA_character_
)

metadata_sample <- dplyr::bind_rows(metadata_equity, metadata_crypto)

# ---------------------------------------------------------------------------
# Factors: Fama-French 3-factor daily, matches registry `factors` schema
# exactly (date, factor_name, value, dataset, frequency, source, updated_at).
# ---------------------------------------------------------------------------
FACTOR_NAMES <- c("Mkt-RF", "SMB", "HML", "RF")
factors_sample <- do.call(rbind, lapply(FACTOR_NAMES, function(fname) {
  tibble::tibble(
    date        = FACTOR_DATES,
    factor_name = fname,
    value       = round(rnorm(length(FACTOR_DATES), mean = if (fname == "RF") 0.01 else 0, sd = 0.5), 2),
    dataset     = "FF3",
    frequency   = "daily",
    source      = "french",
    updated_at  = UPDATED_AT
  )
}))

# ---------------------------------------------------------------------------
# Macro: FRED-style daily series, matches registry `macro_daily` schema
# exactly (date, value, series_id, source) -- no updated_at column (the
# real macro_daily.parquet, per scripts/fetch_macro.R, does not carry one).
# 16 series so hd_macro_series() length >= 15 stays a real assertion.
# ---------------------------------------------------------------------------
MACRO_SERIES <- tibble::tribble(
  ~series_id,    ~level,   ~vol,
  "SP500",       4700,     30,
  "VIXCLS",      15,       2,
  "VXVCLS",      17,       2,
  "DGS2",        4.3,      0.05,
  "DGS10",       4.1,      0.05,
  "DGS30",       4.3,      0.05,
  "DFF",         5.33,     0.01,
  "FEDFUNDS",    5.33,     0.01,
  "T10Y2Y",      -0.2,     0.03,
  "T10Y3M",      0.1,      0.03,
  "GDP",         27000,    50,
  "UNRATE",      3.8,      0.05,
  "CPIAUCSL",    310,      0.3,
  "PCEPI",       123,      0.2,
  "DCOILWTICO",  75,       1.5,
  "DTWEXBGS",    120,      0.5
)
stopifnot(nrow(MACRO_SERIES) >= 15L, "SP500" %in% MACRO_SERIES$series_id)

macro_sample <- do.call(rbind, lapply(seq_len(nrow(MACRO_SERIES)), function(i) {
  s <- MACRO_SERIES[i, ]
  tibble::tibble(
    date      = MACRO_DATES,
    value     = round(s$level + cumsum(rnorm(length(MACRO_DATES), 0, s$vol * 0.1)), 3),
    series_id = s$series_id,
    source    = "fred"
  )
}))

# ---------------------------------------------------------------------------
# Write parquets. arrow::write_parquet() preserves POSIXct as TIMESTAMP and
# Date as DATE, matching the real HF schemas.
# ---------------------------------------------------------------------------
arrow::write_parquet(equity_sample, file.path(out_dir, "equity_sample.parquet"))
arrow::write_parquet(crypto_sample, file.path(out_dir, "crypto_sample.parquet"))
arrow::write_parquet(metadata_sample, file.path(out_dir, "metadata_sample.parquet"))
arrow::write_parquet(factors_sample, file.path(out_dir, "factors_sample.parquet"))
arrow::write_parquet(macro_sample, file.path(out_dir, "macro_sample.parquet"))

# ---------------------------------------------------------------------------
# Fundamentals: SEC EDGAR XBRL revision-triangle sample (#553/#554/#555).
#
# Appended AFTER every other write_parquet() call above so the RNG stream
# consumed while generating equity/crypto/metadata/factors/macro is
# untouched by this block -- regenerating this script must not change
# those five files' numeric content.
#
# Provenance: fabricated by this seeded generator, same discipline as the
# rest of this script -- NOT derived from any real filing. Ticker symbols
# reuse two real large-cap labels already used above (AAPL, MSFT); the
# period_end/first_filed timing follows plausible SEC filing-lag windows
# (10-K ~60 calendar days, 10-Q ~42 days) so the fixture exercises
# realistic point-in-time cutoffs for hd_fundamentals(as_of=). Every 5th
# row is deterministically marked restated=TRUE (i %% 5L == 0L) so both
# the restated and non-restated paths are covered without depending on
# random chance.
# ---------------------------------------------------------------------------
FUND_TICKERS <- c("AAPL", "MSFT")
FUND_TAGS <- c("Revenues", "EarningsPerShareDiluted",
               "StockholdersEquity",
               "NetCashProvidedByUsedInOperatingActivities")
FUND_PERIODS <- tibble::tribble(
  ~fiscal_period, ~period_end,            ~filing_lag_days, ~form,
  "2023Q4",        as.Date("2023-09-30"),  60L,              "10-K",
  "2024Q1",        as.Date("2023-12-31"),  42L,              "10-Q",
  "2024Q2",        as.Date("2024-03-31"),  42L,              "10-Q"
)

fund_rows <- list()
fi <- 0L
for (tk in FUND_TICKERS) {
  for (tag in FUND_TAGS) {
    for (p in seq_len(nrow(FUND_PERIODS))) {
      fi <- fi + 1L
      period_end  <- FUND_PERIODS$period_end[p]
      first_filed <- period_end + FUND_PERIODS$filing_lag_days[p]
      base_val <- switch(tag,
        Revenues = round(runif(1, 5e10, 1.2e11), 2),
        EarningsPerShareDiluted = round(runif(1, 1.0, 3.0), 4),
        StockholdersEquity = round(runif(1, 5e10, 2e11), 2),
        NetCashProvidedByUsedInOperatingActivities = round(runif(1, 1e10, 4e10), 2)
      )
      restated <- (fi %% 5L == 0L)
      latest_val <- if (restated) round(base_val * (1 + runif(1, 0.01, 0.03)), 4) else base_val
      fund_rows[[fi]] <- tibble::tibble(
        ticker         = tk,
        fiscal_period  = FUND_PERIODS$fiscal_period[p],
        period_end     = period_end,
        first_filed    = first_filed,
        xbrl_tag       = tag,
        original_value = base_val,
        latest_value   = latest_val,
        restated       = restated,
        source         = paste0("SEC EDGAR XBRL (", FUND_PERIODS$form[p], ", synthetic)")
      )
    }
  }
}
fundamentals_sample <- dplyr::bind_rows(fund_rows)
stopifnot(
  nrow(fundamentals_sample) == length(FUND_TICKERS) * length(FUND_TAGS) * nrow(FUND_PERIODS),
  any(fundamentals_sample$restated), any(!fundamentals_sample$restated),
  all(fundamentals_sample$first_filed > fundamentals_sample$period_end)
)
arrow::write_parquet(fundamentals_sample, file.path(out_dir, "fundamentals_sample.parquet"))

cat("\nWrote sample parquets to", out_dir, "\n")
cat("equity_sample:   ", nrow(equity_sample), "rows,", length(EQUITY_TICKERS), "tickers\n")
cat("crypto_sample:   ", nrow(crypto_sample), "rows,", length(CRYPTO_TICKERS), "tickers\n")
cat("metadata_sample: ", nrow(metadata_sample), "rows\n")
cat("factors_sample:  ", nrow(factors_sample), "rows\n")
cat("macro_sample:    ", nrow(macro_sample), "rows,", nrow(MACRO_SERIES), "series\n")
cat("fundamentals_sample: ", nrow(fundamentals_sample), "rows,",
    length(FUND_TICKERS), "tickers,", length(FUND_TAGS), "tags,",
    sum(fundamentals_sample$restated), "restated\n")
cat("EQUITY_DATES:    ", format(min(EQUITY_DATES)), "to", format(max(EQUITY_DATES)), "\n")
cat("CRYPTO_DATES:    ", format(min(CRYPTO_DATES)), "to", format(max(CRYPTO_DATES)), "\n")
