# Tests for the bundled sample-data fixtures (inst/extdata/sample/*.parquet)
# generated by data-raw/make_sample_data.R (issue #580 Phase 2).
#
# These fixtures back HD_USE_SAMPLE_DATA=1 (see helper-sample.R and
# hd_dataset_source() in R/registry.R). This file asserts the known
# contents the hermetic accessor tests in test-query.R / test-ranked.R /
# test-registry.R rely on, so a future regeneration that silently drops a
# ticker or renames a column fails here first, with a clear message,
# instead of producing confusing failures scattered across the suite.

test_that("equity sample has >= 50 tickers including AAPL and MSFT", {
  skip_if_not_installed("arrow")
  eq <- arrow::read_parquet(historicaldata:::hd_sample_path("equity_daily"))
  tickers <- unique(eq$ticker)
  expect_true(length(tickers) >= 50)
  expect_true(all(c("AAPL", "MSFT") %in% tickers))
})

test_that("equity sample columns match the registry schema (legacy 'adjusted' name)", {
  skip_if_not_installed("arrow")
  eq <- arrow::read_parquet(historicaldata:::hd_sample_path("equity_daily"))
  expect_setequal(
    names(eq),
    c("date", "open", "high", "low", "close", "adjusted",
      "volume", "ticker", "source", "asset_class", "updated_at")
  )
  expect_true(inherits(eq$date, "POSIXct"))
  expect_equal(nrow(eq[eq$ticker == "AAPL", ]), 32L)
})

test_that("crypto sample has BTC and ETH with POSIXct dates", {
  skip_if_not_installed("arrow")
  cr <- arrow::read_parquet(historicaldata:::hd_sample_path("crypto_daily"))
  expect_setequal(unique(cr$ticker), c("BTC", "ETH"))
  expect_true(inherits(cr$date, "POSIXct"))
  expect_equal(nrow(cr[cr$ticker == "BTC", ]), 40L)
})

test_that("metadata sample covers AAPL, MSFT, BTC, ETH with market_cap/volume_avg", {
  skip_if_not_installed("arrow")
  md <- arrow::read_parquet(historicaldata:::hd_sample_path("metadata"))
  expect_true(all(c("AAPL", "MSFT", "BTC", "ETH") %in% md$ticker))
  key_rows <- md[md$ticker %in% c("AAPL", "MSFT", "BTC", "ETH"), ]
  expect_true(all(!is.na(key_rows$market_cap)))
  expect_true(all(!is.na(key_rows$volume_avg)))
})

test_that("factors sample has FF3 daily data including Mkt-RF", {
  skip_if_not_installed("arrow")
  fac <- arrow::read_parquet(historicaldata:::hd_sample_path("factors"))
  expect_true(all(fac$dataset == "FF3"))
  expect_true(all(fac$frequency == "daily"))
  expect_true("Mkt-RF" %in% fac$factor_name)
})

test_that("macro sample has >= 15 series including SP500", {
  skip_if_not_installed("arrow")
  mac <- arrow::read_parquet(historicaldata:::hd_sample_path("macro_daily"))
  series <- unique(mac$series_id)
  expect_true(length(series) >= 15)
  expect_true("SP500" %in% series)
  expect_snapshot(sort(series))
})

test_that("equity sample ticker universe is stable (snapshot)", {
  skip_if_not_installed("arrow")
  eq <- arrow::read_parquet(historicaldata:::hd_sample_path("equity_daily"))
  expect_snapshot(sort(unique(eq$ticker)))
})

test_that("sample fixture schemas are stable (snapshot)", {
  skip_if_not_installed("arrow")
  schemas <- lapply(
    c("equity_daily", "crypto_daily", "macro_daily", "factors", "metadata"),
    function(ds) sort(names(arrow::read_parquet(historicaldata:::hd_sample_path(ds))))
  )
  names(schemas) <- c("equity_daily", "crypto_daily", "macro_daily", "factors", "metadata")
  expect_snapshot(schemas)
})

test_that("hd_dataset_source() falls back to hd_sample_path() only when HD_USE_SAMPLE_DATA is set", {
  withr::local_envvar(c(HD_USE_SAMPLE_DATA = "1"))
  expect_equal(
    historicaldata:::hd_dataset_source("equity_daily"),
    historicaldata:::hd_sample_path("equity_daily")
  )
})

test_that("hd_dataset_source() returns the live hf:// URL when HD_USE_SAMPLE_DATA is unset", {
  withr::local_envvar(c(HD_USE_SAMPLE_DATA = NA))
  expect_equal(
    historicaldata:::hd_dataset_source("equity_daily"),
    historicaldata:::hd_datasets()[["equity_daily"]]$url
  )
  expect_true(grepl("^hf://", historicaldata:::hd_dataset_source("equity_daily")))
})
