#!/usr/bin/env bash
# Regenerate docs/api-historicaldata.md from packages/historicaldata.
# Triggered manually before any commit that changes packages/historicaldata/R/.
# Future: hook this into a Quarto pre-render or pre-commit (see JohnGavin/llm issue).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTFILE="$ROOT/docs/api-historicaldata.md"
SHA=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date +%Y-%m-%d)

# Generate pkgctx output to a temp file
TMPFILE=$(mktemp /tmp/pkgctx_output_XXXXXX.md)
nix run github:b-rodrigues/pkgctx -- r "$ROOT/packages/historicaldata" --compact > "$TMPFILE"

# Prepend documentation header
HEADERFILE=$(mktemp /tmp/pkgctx_header_XXXXXX.md)
cat > "$HEADERFILE" << HEADER
<!-- Generated by pkgctx — do not edit manually.
     Command:  nix run github:b-rodrigues/pkgctx -- r packages/historicaldata --compact
     Date:     $DATE
     SHA:      $SHA
     Regenerate: bash scripts/regen_api_context.sh (from repo root)
     See also: docs/index.qmd stat-link for "functions" count. -->
HEADER

cat "$HEADERFILE" "$TMPFILE" > "$OUTFILE"
rm -f "$TMPFILE" "$HEADERFILE"

N=$(grep -c "^kind: function" "$OUTFILE")
echo "Wrote $OUTFILE ($N functions)"
