#!/usr/bin/env bash
# Regenerate docs/api-historicaldata.md from packages/historicaldata.
# Triggered manually before any commit that changes packages/historicaldata/R/.
# Future: hook this into a Quarto pre-render or pre-commit (see JohnGavin/llm issue).
set -euo pipefail

# Graceful degrade: if nix is not available, skip silently (CI or dev
# environments without Nix should not fail hard on a doc-regen script).
if ! command -v nix >/dev/null 2>&1; then
  echo "regen_api_context.sh: nix not found on PATH — skipping pkgctx regen" >&2
  exit 0
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTFILE="$ROOT/docs/api-historicaldata.md"
SHA=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date +%Y-%m-%d)

# Generate pkgctx output to a temp file
TMPFILE=$(mktemp /tmp/pkgctx_output_XXXXXX.md)
nix run github:b-rodrigues/pkgctx -- r "$ROOT/packages/historicaldata" --compact > "$TMPFILE"

# Prepend documentation header
HEADERFILE=$(mktemp /tmp/pkgctx_header_XXXXXX.md)
cat > "$HEADERFILE" << HEADER
<!-- Generated by pkgctx — do not edit manually.
     Command:  nix run github:b-rodrigues/pkgctx -- r packages/historicaldata --compact
     Date:     $DATE
     SHA:      $SHA
     Regenerate: bash scripts/regen_api_context.sh (from repo root)
     See also: docs/index.qmd stat-link for "functions" count. -->
HEADER

cat "$HEADERFILE" "$TMPFILE" > "$OUTFILE"
rm -f "$TMPFILE" "$HEADERFILE"

# Suppress header-only churn: if the only lines that changed vs the committed
# version are the volatile Date:/SHA: header lines, restore the committed file.
# Keeps the Stop hook silent and `git status` clean when the API is unchanged.
# (git diff -I requires git >= 2.30; --no-ext-diff because -I is only
# honoured by git's internal xdiff, not external diff drivers.)
if git -C "$ROOT" ls-files --error-unmatch docs/api-historicaldata.md >/dev/null 2>&1; then
  if git -C "$ROOT" diff --no-ext-diff --quiet -I'^     Date:' -I'^     SHA:' -- docs/api-historicaldata.md; then
    git -C "$ROOT" checkout --quiet -- docs/api-historicaldata.md
    echo "API unchanged (header-only churn suppressed): docs/api-historicaldata.md left at committed version"
    exit 0
  fi
fi

N=$(grep -c "^kind: function" "$OUTFILE")
echo "Wrote $OUTFILE ($N functions)"
