#!/usr/bin/env bash
# Regenerate docs/api-historicaldata.md from packages/historicaldata.
# Triggered manually before any commit that changes packages/historicaldata/R/.
# Future: hook this into a Quarto pre-render or pre-commit (see JohnGavin/llm issue).
set -euo pipefail

# Graceful degrade: if nix is not available, skip silently (CI or dev
# environments without Nix should not fail hard on a doc-regen script).
if ! command -v nix >/dev/null 2>&1; then
  echo "regen_api_context.sh: nix not found on PATH — skipping pkgctx regen" >&2
  exit 0
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTFILE="$ROOT/docs/api-historicaldata.md"
SHA=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date +%Y-%m-%d)

# Temp files. BSD mktemp only substitutes TRAILING X's, so no suffix after them
# (a suffix created a literal file and the next run failed). The trap makes
# sure they never survive a failure.
TMPFILE=$(mktemp /tmp/pkgctx_output_XXXXXX)
HEADERFILE=$(mktemp /tmp/pkgctx_header_XXXXXX)
trap 'rm -f "$TMPFILE" "$HEADERFILE"' EXIT

# Generate pkgctx output. A failure here means pkgctx could not be built or
# run -- the doc's freshness is UNKNOWN, which is not the same as stale.
# Exit 3 = INDETERMINATE (exit-code-conventions).
#
# PKGCTX_BIN (optional, set by CI): path to an already-built pkgctx binary.
# JohnGavin/historical#861's cachix workaround builds pkgctx once via
# `nix build ... -o <path>` (giving a concrete store path a targeted
# `cachix push` can push), then passes that build's bin/pkgctx here so
# this script never has to invoke `nix run` fresh in CI. Local/dev usage
# is unaffected: PKGCTX_BIN is unset, so the `nix run` fallback below
# runs exactly as before.
if [ -n "${PKGCTX_BIN:-}" ]; then
  if [ ! -x "$PKGCTX_BIN" ]; then
    echo "INDETERMINATE: PKGCTX_BIN=$PKGCTX_BIN is not an executable file; docs/api-historicaldata.md freshness was NOT checked" >&2
    exit 3
  fi
  if ! "$PKGCTX_BIN" r "$ROOT/packages/historicaldata" --compact > "$TMPFILE"; then
    echo "INDETERMINATE: could not run PKGCTX_BIN=$PKGCTX_BIN; docs/api-historicaldata.md freshness was NOT checked" >&2
    exit 3
  fi
elif ! nix run github:b-rodrigues/pkgctx -- r "$ROOT/packages/historicaldata" --compact > "$TMPFILE"; then
  echo "INDETERMINATE: could not build/run pkgctx; docs/api-historicaldata.md freshness was NOT checked" >&2
  exit 3
fi

# Prepend documentation header
cat > "$HEADERFILE" << HEADER
<!-- Generated by pkgctx — do not edit manually.
     Command:  nix run github:b-rodrigues/pkgctx -- r packages/historicaldata --compact
     Date:     $DATE
     SHA:      $SHA
     Regenerate: bash scripts/regen_api_context.sh (from repo root)
     See also: docs/index.qmd stat-link for "functions" count. -->
HEADER

cat "$HEADERFILE" "$TMPFILE" > "$OUTFILE"

# Suppress header-only churn: if the only lines that changed vs the committed
# version are the volatile Date:/SHA: header lines, restore the committed file.
# Keeps the Stop hook silent and `git status` clean when the API is unchanged.
# (git diff -I requires git >= 2.30; --no-ext-diff because -I is only
# honoured by git's internal xdiff, not external diff drivers.)
if git -C "$ROOT" ls-files --error-unmatch docs/api-historicaldata.md >/dev/null 2>&1; then
  if git -C "$ROOT" diff --no-ext-diff --quiet -I'^     Date:' -I'^     SHA:' -- docs/api-historicaldata.md; then
    git -C "$ROOT" checkout --quiet -- docs/api-historicaldata.md
    echo "API unchanged (header-only churn suppressed): docs/api-historicaldata.md left at committed version"
    exit 0
  fi
fi

N=$(grep -c "^kind: function" "$OUTFILE")
echo "Wrote $OUTFILE ($N functions)"
